### ISSUE TITLE
[BUG] Amiibo NFC Emulation error on all except last playlist entry?

### ISSUE THREAD

**Issue by zmike808** [acegoal07/FlipperZero_NFC_Playlist#33]
**Describe the bug**
If I setup say 10 different NFC amiibo files that emulate fine manually on their own. Playlist format will look like
/ext/nfc/.../link.nfc
....
/ext/nfc/.../guardian.nfc
What seems to happen with 100% certainty is that it will claim all NFCs have an error except for the last entry in the playlist. What gives?

The exact error message is "ERROR invalid file: <filename>" Then it will proceed to the last one eventually and say "Emulating <filename>".

Currently scouring the source for a reason as to why, since this would make my BOTW amiibo farm much easier, but I'm unfamiliar completely with flippers API and such, and my C is rusty af. But we'll see I guess.....

**Comment by acegoal07** [comment]
Is it possible for you to provide me with the full playlist data and also does this occur with when you try less amiibos?

**Comment by acegoal07** [comment]
@zmike808 I've been unable to replicate this issue but this could be because of changes i have made to emulation scene in v2.4 so i will leave the issue open and if the problem persists in v2.4 I'll do more testing with your help to try find the cause of this issue

**Comment by Hessevalentino** [comment]
Hi, I have exactly the same problem. Can I send you the necessary playlist data and the files themselves?
LIST: 
/ext/nfc/t2/3E92AC82C99095.nfc
/ext/nfc/t2/4F8CD236FA89C5.nfc
/ext/nfc/t2/7F3ABC8FE7BF34.nfc
/ext/nfc/t2/20D9746D553CCE.nfc
/ext/nfc/t2/EC4954FB2660F3.nfc

[3E92AC82C99095.csv](https://github.com/user-attachments/files/16950148/3E92AC82C99095.csv)
[4F8CD236FA89C5.csv](https://github.com/user-attachments/files/16950149/4F8CD236FA89C5.csv)
[7F3ABC8FE7BF34.csv](https://github.com/user-attachments/files/16950150/7F3ABC8FE7BF34.csv)
[20D9746D553CCE.csv](https://github.com/user-attachments/files/16950151/20D9746D553CCE.csv)
[EC4954FB2660F3.csv](https://github.com/user-attachments/files/16950152/EC4954FB2660F3.csv)

The files need to be renamed in the extension to NFC, otherwise it was not possible to upload them. I used this Python to generate the code.

https://github.com/Hessevalentino/NFC-Ultralight-Generator/blob/main/NFC-gen.py

THX 4 Help

**Comment by acegoal07** [comment]
@Hessevalentino Hey are you able to get in contact with me on discord as i am struggling to repeat this issue even when using the files you have provided

**Comment by acegoal07** [comment]
> Problem solved. I just installed FW78e and everything works.🤟

That's amazing, can I ask what firmware your running and also if you know what version the app was on before you updated
